name: Continuous Integration Workflow

on:
    pull_request:
        branches:
            - master
            - dev
        paths:
            - bias_scan/**
    push:
        branches:
            - master
            - dev
        paths:
            - bias_scan/**
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install
              run: make install
            - name: test
              run: make test
            - name: format
              run: make format
            - name: lint
              run: make lint