name: Release Workflow

on:
  release:
      types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install poetry
        run: |
          pipx install poetry
          # poetry config virtualenvs.path .virtualenvs
      
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username "__token__" --password $PYPI_TOKEN